# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import logging
import sys
import dataSet
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 40, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.lstDanhSach = QtWidgets.QListView(self.centralwidget)
        self.lstDanhSach.setGeometry(QtCore.QRect(40, 150, 301, 291))
        self.lstDanhSach.setObjectName("lstDanhSach")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 200, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 340, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 150, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnChup = QtWidgets.QPushButton(self.centralwidget)
        self.btnChup.setGeometry(QtCore.QRect(430, 410, 75, 23))
        self.btnChup.setObjectName("btnChup")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(660, 410, 75, 23))
        self.btnRefresh.setObjectName("btnRefresh")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(550, 220, 113, 20))
        self.txtID.setObjectName("txtID")
        self.txtMaSV = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMaSV.setGeometry(QtCore.QRect(550, 260, 113, 20))
        self.txtMaSV.setObjectName("txtMaSV")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 220, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 260, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 300, 91, 16))
        self.label_7.setObjectName("label_7")
        self.txtTenSv = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTenSv.setGeometry(QtCore.QRect(550, 300, 113, 21))
        self.txtTenSv.setObjectName("txtTenSv")
        self.btnTraining = QtWidgets.QPushButton(self.centralwidget)
        self.btnTraining.setGeometry(QtCore.QRect(540, 450, 75, 23))
        self.btnTraining.setObjectName("btnTraining")
        self.btnDiemDanh = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiemDanh.setGeometry(QtCore.QRect(430, 490, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.btnDiemDanh.setFont(font)
        self.btnDiemDanh.setObjectName("btnDiemDanh")
        self.rdNam = QtWidgets.QRadioButton(self.centralwidget)
        self.rdNam.setGeometry(QtCore.QRect(550, 340, 82, 17))
        self.rdNam.setObjectName("rdNam")
        self.rdNu = QtWidgets.QRadioButton(self.centralwidget)
        self.rdNu.setGeometry(QtCore.QRect(620, 340, 82, 17))
        self.rdNu.setObjectName("rdNu")
        self.btnMoExcel = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoExcel.setGeometry(QtCore.QRect(660, 490, 75, 23))
        self.btnMoExcel.setObjectName("btnMoExcel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Định nghĩa hàm lấy tất cả dữ liệu từ database
        def getProfile():
            conn = sqlite3.connect("FaceBase.db")
            mycursor = conn.cursor()
            mycursor.execute("SELECT * FROM People")
            myresult = mycursor.fetchall()
            return myresult

        # Lấy dữ liệu
        entries = getProfile()
        # logging.error(entries[0])

        # Fill data sinh viên vào listview
        model = QtGui.QStandardItemModel()
        self.lstDanhSach.setModel(model)
        for i in entries:
            row = (str(i[0]), str(i[2]), i[1])
            student = "-----".join(row)
            model.appendRow(QtGui.QStandardItem(student))

        # Set event nút Refresh
        # self.btnRefresh.clicked.connect(self.txtID.setText(""))
        self.btnDiemDanh.clicked.connect(lambda:self.close())

    def calcTotal(self):        
        call(["python", "dataSet.py"])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DIEM DANH SINH VIEN"))
        self.label_3.setText(_translate("MainWindow", "Gioi tinh"))
        self.label_4.setText(_translate(
            "MainWindow", "Nhap thong tin sinh vien"))
        self.btnChup.setText(_translate("MainWindow", "Chup anh"))
        self.btnRefresh.setText(_translate("MainWindow", "Refresh"))
        self.label_5.setText(_translate("MainWindow", "ID"))
        self.label_6.setText(_translate("MainWindow", "Ma sinh vien"))
        self.label_7.setText(_translate("MainWindow", "Ten sinh vien"))
        self.btnTraining.setText(_translate("MainWindow", "Training"))
        self.btnDiemDanh.setText(_translate("MainWindow", "Diem danh"))
        self.rdNam.setText(_translate("MainWindow", "Nam"))
        self.rdNu.setText(_translate("MainWindow", "Nu"))
        self.btnMoExcel.setText(_translate("MainWindow", "Mo Excel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
